# Generated by Django 5.1.7 on 2025-03-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_candy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
