# Generated by Django 5.1.7 on 2025-04-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0006_alter_candy_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candy',
            name='categoria',
        ),
    ]
