# Generated by Django 5.1.7 on 2025-04-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0008_candy_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candy.categoriacandy'),
        ),
    ]
